// Docs: engine/webgpu/index.md — usage, recipes & traps (this file = exact type signatures)
export { World3d, Mesh3d, Box3d, Billboard3d, BlobShadow3d, Group3d, blobParams } from './world3d.js';
export { Wisp3d, Trail3d, resampleTrail, crTrail } from './world3d.js';
export type { Group3dConfig, World3dOptions, Mesh3dConfig, Box3dConfig, Billboard3dConfig, BlobShadow3dConfig, BeamConfig, WispConfig, Trail3dOptions, } from './world3d.js';
export { Particles3d, SurfaceSampler } from './particles3d.js';
export type { Emit3dOptions, Burst3dOptions, Fx3dWriter } from './particles3d.js';
export { GpuParticles, GpuEmitter, packForces, MAX_GPU_FORCES, pcg, rand01, vnoise3, curl3, inSpawnWindow, spawnGpuParticle, stepGpuParticle, wrap1, buildGpuParticleComputeWGSL, buildGpuParticleRenderWGSL, GPU_PARTICLE_LAYOUT, } from './particles-gpu.js';
export type { GpuEmitterOptions, GpuForce, GpuP, GpuSpawn } from './particles-gpu.js';
export { Lights3d, Light3d, buildClusterWGSL, froxelBounds, zSlice, binLightsCpu, clusterNear, selectLights, LIGHT_FLOATS, MAX_LIGHTS, CLUSTER_X, CLUSTER_Y, CLUSTER_Z, CLUSTER_COUNT, MAX_PER_CLUSTER, LU_FLOATS } from './lights3d.js';
export type { LightConfig, ClusterCfg } from './lights3d.js';
export { SsaoPass, ssaoKernel, buildSsaoWGSL, buildSsaoBlurWGSL, buildSsaoCompositeWGSL } from './ssao.js';
export type { SsaoOptions } from './ssao.js';
export { RaysPass } from './rays.js';
export type { RaysOptions } from './rays.js';
export { Flare3dLayer } from './flare3d.js';
export { Model3d, AnimatedModel3d, fitVerts, rgbHex, cpuSkin } from './model3d.js';
export type { ModelConfig } from './model3d.js';
export { parseObj, parseMtl } from './obj.js';
export type { ObjData, ObjGroup, ObjMaterial } from './obj.js';
export { parseGlb } from './glb.js';
export { loadModelData } from './model-data.js';
export type { ModelData } from './model-data.js';
export type { GlbData, GlbMaterial, GlbImage, GlbPrimitiveOut, GlbRig, GlbNodeOut, GlbChannel, GlbAnimOut, GlbSkinOut, } from './glb.js';
export { Heightfield, Terrain3d, DeformMap, chunkVerts, deformPatchVerts, bakeColormapPixels, bakeGrainField, hash2, pickChunks, TERRAIN_SURFACES } from './terrain3d.js';
export type { TerrainOptions, TerrainBand, TerrainShape, TerrainSurface, TerrainChunk, DeformOptions } from './terrain3d.js';
export { Grass3d } from './grass3d.js';
export type { GrassOptions } from './grass3d.js';
export { Voxels3d, VoxelWorld, VoxelBody, VoxelAgent, BLOCKS, BLOCK, TILES, bakeTiles, halveRGBA, meshChunk, raycastVoxel, vertexAO, faceTile, voxelTerrain, FACES, AO_LEVELS, VOX_FLOATS, } from './voxel3d.js';
export type { VoxelOptions, VoxelWorldOptions, VoxelHit, BlockDef, VoxelTerrainType, VoxelTerrainOptions, VoxelBodyOptions, VoxelAgentMode, VoxelAgentOptions, } from './voxel3d.js';
export { VoxelEditor } from './voxeledit3d.js';
export type { VoxelEditorOptions, VoxelEditInput, VoxelEditEvent, VoxelHitEvent, VoxelEditResult, } from './voxeledit3d.js';
export { Sky3d, Sky3dLayer, skyState, constellationDirs } from './sky3d.js';
export type { SkyOptions, SkyState } from './sky3d.js';
export { Water3d, Water3dLayer, WaterWell, gerstnerY, gerstnerXZ, steepNorm, ribbonVerts, WATER_PRESETS, WATER_TINTS, rippleFbm, bakeRippleField, RIPPLE_TILE } from './water3d.js';
export type { WaterOptions, WaterWellOptions, WaveDef, WaterPreset, WaterTint } from './water3d.js';
export { Underwater3d, Underwater3dLayer, UNDERWATER_PRESETS, submersionState, absorb, underwaterFog, bakeCausticField } from './underwater3d.js';
export type { UnderwaterOptions, UnderwaterPreset, UnderwaterPresetName, CausticOptions } from './underwater3d.js';
export { Vector3dLayer, VectorShape3d, wireframeEdges, polylinesToSegs, buildLine3dWGSL, LINE3D_FLOATS } from './vector3d.js';
export type { VectorShape3dOptions } from './vector3d.js';
export { OrbitRig, scaleAboutPoint } from './orbit3d.js';
export type { OrbitOptions } from './orbit3d.js';
export { Agents3d, Agent3d, Field3d, Obstacle3d, SpatialHash3, AGENT_PRESETS, neighborsBrute, integrateAgent, writePose, dampAngle, } from './agents3d.js';
export type { AgentsOptions, AgentConfig, BehaviorSpec, FieldOptions, ObstacleOptions, TargetLike, Vec3, } from './agents3d.js';
export { NavGrid, FlowField } from './navgrid3d.js';
export type { NavGridOptions, NavVec3 } from './navgrid3d.js';
export { NavMesh3d, Crowd3d, buildNavMesh, terrainMesh } from './agentnav3d.js';
export type { NavMeshOptions, PathPlanner } from './agentnav3d.js';
