// Docs: engine/webgpu/index.md — usage, recipes & traps (this file = exact type signatures)
export { Game } from './game.js';
export type { GameOptions, ViewRect } from './game.js';
export * from './util.js';
export { Sprite, overlaps } from './sprite.js';
export type { SpriteConfig, AnimDef } from './sprite.js';
export { Scene, separate } from './scene.js';
export type { SceneClass, SceneRoster, SpriteClass } from './scene.js';
export { Physics } from './physics.js';
export type { Contact } from './physics.js';
export { TileGrid } from './tile-grid.js';
export { CollisionGrid, type TileDef, type TileDefs, type TraceResult, type SlopeNormal, type CollisionGridLike, } from './collision-grid.js';
export { Tilemap } from './tilemap.js';
export type { TileAnim, TileDrawLike } from './tilemap.js';
export { Maze } from './maze.js';
export type { Dir, MazeOptions, MazeAlgorithm, RoomOptions, ExitSpec, Exit, Room, TileOptions, WallSeg, } from './maze.js';
export { FlowGrid } from './flowgrid.js';
export type { FlowGridOptions, FlowDir, } from './flowgrid.js';
export { Track, TrackWalker } from './track.js';
export type { TrackData, TrackEdgeData, TrackEdge, TrackOptions, } from './track.js';
export { Dungeon } from './dungeon.js';
export type { DungeonOptions, DungeonRoom, DungeonTileOptions, RoomTag, } from './dungeon.js';
export { Cave } from './cave.js';
export type { CaveOptions, CaveTileOptions, } from './cave.js';
export { FogGrid } from './fog.js';
export type { FogGridOptions, FogLight, FogState, LightFalloff, } from './fog.js';
export { Visibility2d } from './visibility2d.js';
export type { Segment, RayHit2d, } from './visibility2d.js';
export { Lights2d } from './lights2d.js';
export type { Light2d, PointLight2dOptions, SpotLight2dOptions, } from './lights2d.js';
export { loadLevel, getMapByName, type LevelData, type LevelSpriteData, type LevelLayerData, } from './level.js';
export { Effector, AreaEffector, SurfaceEffector, PointEffector, BuoyancyEffector, type Falloff, type AreaEffectorOptions, type SurfaceEffectorOptions, type PointEffectorOptions, type BuoyancyEffectorOptions, } from './effectors.js';
export { Joint, type JointMode, type JointOptions } from './joints.js';
export { SpritePool } from './sprite-pool.js';
export type { PooledClass, PoolableSprite } from './sprite-pool.js';
export { Path, PathWalker, type PathData, type PathSegmentData, type PathOptions, type PathEase, type PathPoint, } from './path.js';
export { on, solid, type HitFn, type EventFn, type HitReg, type EventReg, type SolidReg, type EventDescriptor, } from './glue.js';
export { DefaultTitle, DefaultGameOver } from './defaults.js';
export { Preload, LoadingScene, LOADING_MIN_MS, loadingBarProgress, easeLoadingFill } from './preload.js';
export { loadImage, loadText, loadJson, loadBinary, loadFont, getImage, isImageCached, isTextCached, isBinaryCached, isModelCached, isFontCached, isFontUsable, fontsSettled } from './assets.js';
export { Input, KEY } from './input.js';
export type { KeyCode } from './input.js';
export { PointerTracker, spriteContainsPoint } from './pointer.js';
export type { Pointer, PointerEventBase, TapEvent, DoubleTapEvent, LongPressEvent, PanEvent, SwipeEvent, SwipeDirection, TapHandler, DoubleTapHandler, LongPressHandler, PanHandler, SwipeHandler, PointerHandler, GestureOptions, } from './pointer.js';
export { SceneInput } from './scene-input.js';
export type { KeyState, InteractiveSprite } from './scene-input.js';
export { Camera } from './camera.js';
export { Screen } from './screen.js';
export { Assets } from './game-assets.js';
export { Draw } from './draw.js';
export type { SpriteOpts, PanelState } from './draw.js';
export { FixedClock } from './clock.js';
export { rgba, WHITE } from './color.js';
export type { Rgba } from './color.js';
export { VectorLayer, VectorShape, VecTrail, VecStarfield, buildLineWGSL, buildFillWGSL, buildFill, polySegs, chainJoins, segJoins, segmentStyles, shapeOrigin, spawnFragment, stepFragment, fragmentAlpha, clipToScissor, LINE_FLOATS, FILL_FLOATS, XFORM_FLOATS, } from './vector.js';
export type { VecClipRect, VecFill, VecTrailOptions, LineStyle, VectorShapeOptions, VecPt, VecFragment, VecEmitOptions, VecShapeKind, VecColorSource, PackedStyle, VecStar, VecStarMode, VecStarfieldOptions } from './vector.js';
export type { VecTextOptions, VecTextAlign } from './vecfont.js';
export type { RingSection, RingSectionOptions, Tube, TubeOptions, TubeProfile, LanePose, Vec3, WireModel, WireCamera, WireView, WireEdge, WireBounds } from './vecshapes.js';
export { Gpu, installErrorOverlay, shaderModule, BITS } from './gpu.js';
export type { GpuOptions } from './gpu.js';
export { Atlas, packShelves, textureFromCanvas, rasterText } from './atlas.js';
export type { Frame, PackedBox } from './atlas.js';
export { BitmapFont, bakeFont } from './font.js';
export type { FontOptions, Glyph } from './font.js';
export { MsdfFont, parseMsdfFont, msdfTextureFrom } from './msdf-font.js';
export type { MsdfFontData, MsdfGlyph, MsdfFontJSON } from './msdf-font.js';
export { MsdfRenderer, packColor, packParams, packSolidParams, packDashParams, SOLID_PARAMS, BITMAP_PARAMS } from './msdf.js';
export { MsdfText } from './msdf-text.js';
export { UiRenderer, packUiColor, UI_STRIDE, sameClip, clipToPixels } from './ui.js';
export type { ClipRect } from './ui.js';
export { UI_STYLES, defineUiStyle, resolveUiStyle } from './ui-style.js';
export type { UiStyle, UiStateStyle, UiState, UiRadius, ResolvedUiStyle } from './ui-style.js';
export { Ui, UI_THEMES, buildUiTheme, isLatinText } from './ui-widgets.js';
export type { MsdfAlign, MsdfColor, MsdfOutline, MsdfShadow, MsdfRule, MsdfHighlight, MsdfStyle, MsdfSegment, MsdfTextOptions, MsdfDrawOptions, } from './msdf-text.js';
export { UnicodeText, detectDirection, isRtlCodePoint, breakOpportunities, graphemes } from './unicode-text.js';
export type { UnicodeAlign, UnicodeDirection, UnicodeTextOptions, UnicodeDrawOptions, TextFill, TextGradient, TextStroke, TextShadow, TextGlow, TextBackground, TextRule, TextAppearance, TextStateStyle, } from './unicode-text.js';
export { textOverlaps, makeBounds, transformedBounds, boundsOverlap, boundsIntersection, boundsUnion, } from './text-bounds.js';
export type { TextBounds, TextTransform, BoundedText, TextItem, TextOverlap } from './text-bounds.js';
export { Particles, RAMPS, resolveRamp } from './particles.js';
export type { EmitOptions, RampName } from './particles.js';
export type { Particles3d, SurfaceSampler } from './particles3d.js';
export type { Emit3dOptions, Burst3dOptions, Fx3dWriter } from './particles3d.js';
export type { GpuParticles, GpuEmitter } from './particles-gpu.js';
export type { GpuEmitterOptions, GpuForce, GpuP, GpuSpawn } from './particles-gpu.js';
export { particleCanvas } from './particle-tex.js';
export type { ParticleTexKind, ParticleTexOptions } from './particle-tex.js';
export { PostChain, PostHandle, PostLayer } from './post.js';
export { BackdropChain, BackdropHandle, BackdropLayer, BACKDROPS, BACKDROP_PACK, buildBackdropWGSL } from './backdrop.js';
export { VfxSystem, TrailEmitter, registerVfx, resolveVfx, VFX, VFX_PACK } from './vfx.js';
export { DebugOverlay, normalizeDebug } from './debug.js';
export type { DebugOptions } from './debug.js';
export type { VfxDef, BurstLayer, TrailSparks } from './vfx.js';
export type { BackdropDef, BackgroundSource } from './backdrop.js';
export { EFFECTS, EFFECT_PACK, buildEffectWGSL, effectDefaults, effectParamIndex, MAX_EFFECT_PARAMS } from './effects.js';
export type { EffectDef } from './effects.js';
export { FxBatch, fxNeedsShader } from './fxbatch.js';
export type { SpriteFx } from './fxbatch.js';
export { GlowPass } from './glowpass.js';
export { GridBatch, facing, buildGridWGSL } from './gridbatch.js';
export type { Deform, DeformDef, GridBatchOptions } from './gridbatch.js';
export type { World3d, Mesh3d, Box3d, Billboard3d, BlobShadow3d, Group3d } from './world3d.js';
export type { Group3dConfig } from './world3d.js';
export { eulerToQuat, quatMul, quatRotate, quatToEuler, composeChain, lookAtEuler, forward } from './transform3d.js';
export type { Quat, ParentLike } from './transform3d.js';
export { McControls, mcControls, cubeEdges } from './mccontrols.js';
export type { McOptions, McHotbar, McWalkSpeeds } from './mccontrols.js';
export type { World3dOptions, Mesh3dConfig, Box3dConfig, Billboard3dConfig, BlobShadow3dConfig, BeamConfig } from './world3d.js';
export { Physics2d, Body2d } from './physics2d.js';
export type { Physics2dOptions, BindOptions as Bind2dOptions, BindShapeOptions, ChainOptions, DebugDrawOptions, DebugDrawTarget, Joint2d, PinOptions, RopeOptions, SliderOptions as Slider2dOptions, WheelOptions as Wheel2dOptions, GrabOptions as Grab2dOptions, Grab2d, RayHit, } from './physics2d.js';
export { Physics3d, Body3d, Character3d } from './physics3d.js';
export type { Physics3dOptions, MeshLike3d, BindOptions as Bind3dOptions, Character3dOptions, Joint3d, HingeOptions, SliderOptions as Slider3dOptions, SpringOptions, SocketOptions, WheelOptions as Wheel3dOptions, GrabOptions as Grab3dOptions, } from './physics3d.js';
export { Builder } from './geometry3d.js';
export { Solid, transformVerts, unionVerts, subtractVerts, intersectVerts } from './csg3d.js';
export type { Transform } from './csg3d.js';
export type { OrbitRig } from './orbit3d.js';
export type { OrbitOptions } from './orbit3d.js';
export type { Agents3d, Agent3d, Field3d, Obstacle3d, SpatialHash3 } from './agents3d.js';
export type { AgentsOptions, AgentConfig, BehaviorSpec, FieldOptions, ObstacleOptions, TargetLike } from './agents3d.js';
export type { NavGrid, FlowField, NavGridOptions, NavVec3 } from './navgrid3d.js';
export type { NavMesh3d, Crowd3d, NavMeshOptions, PathPlanner } from './agentnav3d.js';
export type { ObjData, ObjGroup, ObjMaterial } from './obj.js';
export type { GlbData, GlbMaterial, GlbImage, GlbPrimitiveOut, GlbRig, GlbNodeOut, GlbChannel, GlbAnimOut, GlbSkinOut, } from './glb.js';
export { quatSlerp, trsToMat4, mat4MulTo, sampleChannel, composeWorlds, jointPalette, decomposeTRS, AnimMixer, } from './anim3d.js';
export { quickhull, hullOfVerts } from './hull3d.js';
export type { Lights3d, Light3d } from './lights3d.js';
export type { LightConfig, ClusterCfg } from './lights3d.js';
export type { SsaoPass } from './ssao.js';
export type { SsaoOptions } from './ssao.js';
export type { Model3d, AnimatedModel3d } from './model3d.js';
export type { ModelConfig } from './model3d.js';
export type { Wisp3d, Trail3d } from './world3d.js';
export type { WispConfig, Trail3dOptions } from './world3d.js';
export { mulberry32, noisePerm, perlin2, fbm2, noiseData, noiseCanvas } from './noise.js';
export type { NoiseTextureOptions, FbmOptions } from './noise.js';
export { cubeVerts, sphereVerts, cylinderVerts, torusVerts, roundedBoxVerts, coneVerts, capsuleVerts, wedgeVerts, planeVerts, panelVerts, discVerts, circleVerts, ringVerts, torusKnotVerts, tubeVerts, polyhedronVerts, latheVerts, shapeVerts, extrudeVerts, earClip, } from './geometry3d.js';
export { vec3, mat4Perspective, mat4Ortho, mat4LookAt, mat4Mul, mat4Project, mat4Inverse, viewBasis, frustumPlanes, sphereVsFrustum, rayFromNdc, raySphere, rayPlaneY, rayObb, rayObbLocal } from './math3d.js';
export { Path3d, DynamicPath3d, catmullRom3 } from './path3d.js';
export type { Heightfield, Terrain3d, DeformMap } from './terrain3d.js';
export type { TerrainOptions, TerrainBand, TerrainShape, TerrainSurface, TerrainChunk, DeformOptions } from './terrain3d.js';
export { TerrainRider, footprintTaps, buildFootprint } from './rider3d.js';
export type { TerrainRiderOptions, ContactShape } from './rider3d.js';
export type { Grass3d } from './grass3d.js';
export type { GrassOptions } from './grass3d.js';
export type { Voxels3d, VoxelWorld, VoxelBody, VoxelAgent } from './voxel3d.js';
export type { VoxelOptions, VoxelWorldOptions, VoxelHit, BlockDef, VoxelTerrainType, VoxelTerrainOptions, VoxelBodyOptions, VoxelAgentMode, VoxelAgentOptions, } from './voxel3d.js';
export type { VoxelEditor } from './voxeledit3d.js';
export type { VoxelEditorOptions, VoxelEditInput, VoxelEditEvent, VoxelHitEvent, VoxelEditResult, } from './voxeledit3d.js';
export type { Sky3d, Sky3dLayer } from './sky3d.js';
export type { SkyOptions, SkyState } from './sky3d.js';
export type { Water3d, Water3dLayer } from './water3d.js';
export type { WaterOptions, WaterWellOptions, WaterWell, WaveDef, WaterPreset, WaterTint } from './water3d.js';
export type { Underwater3d, Underwater3dLayer } from './underwater3d.js';
export type { UnderwaterOptions, UnderwaterPreset, UnderwaterPresetName, CausticOptions } from './underwater3d.js';
export type { RaysOptions } from './rays.js';
export type { Vector3dLayer, VectorShape3d } from './vector3d.js';
export type { VectorShape3dOptions } from './vector3d.js';
export type { Path3dOptions, PathFrame } from './path3d.js';
export type { V3, Mat4 } from './math3d.js';
export { QuadBatch, Z_RANGE, DEPTH_FORMAT } from './batch.js';
export type { BatchOptions } from './batch.js';
export { Audio, noteFreq, type Sound, type SoundSpec, type SoundFilter, type SoundVibrato, type MusicOptions, } from './audio.js';
export { createStateMachine, type StateMachine, type StateHooks, } from './state.js';
export { Tween, TweenHandle, EASING, type TweenOptions, type TweenGroup, type Ease, } from './tween/index.js';
export { persist } from './persistence.js';
export * as vectorKit from './vectorkit.js';
export type { Segment as VecSegment, Fragment as VecPolyFragment, GravitySource, Body as VecBody } from './vectorkit.js';
export * as colorKit from './colorkit.js';
