// Docs: engine/webgpu/index.md — usage, recipes & traps (this file = exact type signatures)
export { GlWorld3d, Mesh3d, Box3d, Group3d, Billboard3d, BlobShadow3d, Wisp3d, blobParams, MESH_FLOATS, BB_FLOATS, BLOB_FLOATS, FX_FLOATS, type Mesh3dConfig, type Group3dConfig, type Billboard3dConfig, type BlobShadow3dConfig, type WispConfig, } from './webgl3d/world.js';
export { Trail3d, resampleTrail, type Trail3dOptions } from './webgl3d/trails.js';
export { GlVoxels3d, type VoxelFrameU } from './webgl3d/voxels.js';
export { GlWaterLayer, type WaterFrameU } from './webgl3d/water.js';
export { GlUnderwaterLayer } from './webgl3d/underwater.js';
export { GlGrass3d, type GrassFrameU } from './webgl3d/grass.js';
export { buildGlMeshVertGLSL, buildGlMeshFragGLSL, buildGlBillboardVertGLSL, buildGlBillboardFragGLSL, buildGlBlobVertGLSL, buildGlBlobFragGLSL, buildGlFxVertGLSL, buildGlFxFragGLSL, buildGlSkyVertGLSL, buildGlSkyFragGLSL, buildGlLine3dVertGLSL, buildGlLine3dFragGLSL, buildGlTrailVertGLSL, buildGlTrailFragGLSL, buildGlVoxelVertGLSL, buildGlVoxelFragGLSL, buildGlWispVertGLSL, buildGlWispFragGLSL, buildGlShadowVertGLSL, buildGlShadowFragGLSL, buildGlFlareVertGLSL, buildGlFlareFragGLSL, buildGlSunProbeVertGLSL, buildGlSunProbeFragGLSL, buildGlFullscreenVertGLSL, buildGlSsaoFragGLSL, buildGlSsaoBlurFragGLSL, buildGlSsaoCompositeFragGLSL, buildGlRaysFragGLSL, buildGlRaysCompositeFragGLSL, TRAIL_PTS, TRAIL_SEGS, TRAIL_FLOATS, TRAIL_TEXELS, WISP_SEGX, WISP_SEGY, WISP_FLOATS, FLARE_ELEMS, buildGlWaterVertGLSL, buildGlWaterFragGLSL, buildGlFoamDecayFragGLSL, buildGlFoamStampVertGLSL, buildGlFoamStampFragGLSL, buildGlUnderwaterMulFragGLSL, buildGlUnderwaterAddFragGLSL, buildGlShaftVertGLSL, buildGlShaftFragGLSL, buildGlGrassVertGLSL, buildGlGrassFragGLSL, buildGlDeformPatchVertGLSL, buildGlDeformPatchFragGLSL, buildGlBeamVertGLSL, buildGlBeamFragGLSL, buildGlGrassCardVertGLSL, buildGlGrassCardFragGLSL, buildGlPickVertGLSL, buildGlPickFragGLSL, GRASS_SEG, GRASS_BLADE_VERTS, GRASS_BLADE_FLOATS, BEAM_SEGS, BEAM_VERTS, BEAM_INST_FLOATS, GL_MAX_LIGHTS3D, } from './webgl3d/shaders3d.js';
export { loadModelData } from './model-data.js';
