const fs=require('node:fs'),T=require('./timing.js'),D=require('./difficulty.js'),A=require('./action.js'),E=require('./ending.js'),C=require('./choice.js'),I=require('./impact.js'),V=require('./visual.js'),BA=require('./test-baseline-v22-action.cjs'),BD=require('./test-baseline-v22-difficulty.cjs');
const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
const distribution=a=>{const s=a.slice().sort((x,y)=>x-y),p=q=>s.length?s[Math.min(s.length-1,Math.floor((s.length-1)*q))]:null;return {count:s.length,mean:mean(s),min:p(0),p10:p(.1),median:p(.5),p90:p(.9),max:p(1)};};
function context(name,version){const m=require(`./${name}-analyzer-test.json`),e=require(`./${name}-action-evidence-v22.json`),ending=E.detect(m),times=T.createTiming(m).times,energy=t=>T.energyAt(m,t,m.songLength),d=version===22?BD:D,a=version===22?BA:A;
 const rows=a.plan(times,ending.playableEndTime,m,e,d,energy,ending.releaseGap);for(const r of rows){r.playableEnd=ending.playableEndTime;r.releaseGap=ending.releaseGap;}
 C.annotate(rows);C.annotateSelection(rows);return {m,e,ending,times,energy,rows,d};
}
function metrics(ctx){
 const selected=ctx.rows.filter(r=>r.selected);let previous=null;const routes=selected.map((r,i)=>{const xy=ctx.d.position(i,r,375,667,previous),travel=previous?Math.hypot(xy.x-previous.x,xy.y-previous.y):0;previous={...xy,targetTime:r.targetTime};return {index:r.originalBeatIndex,travel};});
 let combo=0,cumulativeMax=0;
 const pointMap=new Map();for(const r of selected){combo++;const points=Math.round(120*Math.min(3,1+Math.floor(combo/10)*.25));cumulativeMax+=points;pointMap.set(r.originalBeatIndex,points);}
 return ctx.d.stages.map(s=>{
  const chosen=selected.filter(r=>r.name===s.name),p=ctx.d.profile(chosen[0]?.targetTime??s.start*ctx.ending.playableEndTime,ctx.ending.playableEndTime),intervals=chosen.slice(1).map((r,i)=>r.targetTime-chosen[i].targetTime),runLengths=[],recovery=[],skipCounts=[];let run=0,last=null;
  for(const r of chosen){if(last&&r.originalBeatIndex!==last.originalBeatIndex+1){runLengths.push(run);run=0;recovery.push(r.targetTime-last.targetTime);skipCounts.push(r.originalBeatIndex-last.originalBeatIndex-1);}run++;last=r;}if(run)runLengths.push(run);
  const histogram={single:0,two:0,three:0,four:0,fivePlus:0};for(const n of runLengths)histogram[n===1?'single':n===2?'two':n===3?'three':n===4?'four':'fivePlus']++;
  const source=ctx.rows.filter(r=>r.name===s.name&&r.targetTime<ctx.ending.playableEndTime);
  return {stage:s.name,startSeconds:p.start*ctx.ending.playableEndTime,endSeconds:p.end*ctx.ending.playableEndTime,targets:chosen.length,sourceCandidates:source.length,density:source.length?chosen.length/source.length:0,targetsPerSecond:chosen.length/((p.end-p.start)*ctx.ending.playableEndTime),targetIntervals:distribution(intervals),recoveryGapSeconds:distribution(recovery),recoverySkippedBeats:distribution(skipCounts),travelPixels:distribution(routes.filter(r=>chosen.some(c=>c.originalBeatIndex===r.index)).map(r=>r.travel)),runHistogram:histogram,longestRun:Math.max(0,...runLengths),multiHitRunsPerSecond:runLengths.filter(n=>n>=2).length/((p.end-p.start)*ctx.ending.playableEndTime),recoveryEventsPerSecond:recovery.length/((p.end-p.start)*ctx.ending.playableEndTime),longRunActionsPerSecond:runLengths.filter(n=>n>=3).reduce((a,b)=>a+b,0)/((p.end-p.start)*ctx.ending.playableEndTime),actionsInRunsAtLeast3:runLengths.filter(n=>n>=3).reduce((a,b)=>a+b,0),baseMaximumPoints:chosen.length*120,maximumPointsWithUnbrokenCombo:chosen.reduce((a,r)=>a+pointMap.get(r.originalBeatIndex),0),overallHitWindow:p.window};
 });
}
function neighborhoodDiagnostics(ctx){const selected=ctx.rows.filter(r=>r.selected&&!['opening','landing'].includes(r.name));const examples=[];let adjacentStronger=0,weakerAttack=0,weakerOnset=0,notLocalPeak=0;
 for(const r of selected){const others=ctx.rows.slice(Math.max(0,r.originalBeatIndex-1),r.originalBeatIndex+2).filter(b=>!b.selected&&b.name===r.name);const stronger=others.filter(b=>b.actionSalience.total>r.actionSalience.total+.025);if(stronger.length)adjacentStronger++;if(others.some(b=>b.actionSalience.components.beatAttack>r.actionSalience.components.beatAttack+.025))weakerAttack++;if(others.some(b=>b.actionSalience.components.onset>r.actionSalience.components.onset+.025))weakerOnset++;if(!r.localPreference.localPeak)notLocalPeak++;
  if(stronger.length&&examples.length<12)examples.push({selectedIndex:r.originalBeatIndex,time:r.targetTime,stage:r.name,salience:r.actionSalience.total,attack:r.actionSalience.components.beatAttack,onset:r.actionSalience.components.onset,reason:r.selectionReason,strongerNeighbors:stronger.map(b=>({index:b.originalBeatIndex,time:b.targetTime,salience:b.actionSalience.total,attack:b.actionSalience.components.beatAttack,onset:b.actionSalience.components.onset,skipReason:b.skippedReason}))});
 }
 return {eligibleSelected:selected.length,selectedWithStrongerAdjacentSkipped:adjacentStronger,selectedWithWeakerAttack:weakerAttack,selectedWithWeakerOnset:weakerOnset,selectedNotLocalPeak:notLocalPeak,examples};
}
function compare(name){const old=context(name,22),now=context(name,23),selected=now.rows.filter(r=>r.selected),skipped=now.rows.filter(r=>!r.selected&&r.targetTime<now.ending.playableEndTime),oldSet=new Set(old.rows.filter(r=>r.selected).map(r=>r.originalBeatIndex)),newSet=new Set(selected.map(r=>r.originalBeatIndex)),before=C.inversions(old.rows),after=C.inversions(now.rows);
 return {sourceCandidates:now.times.length,selectedV22:oldSet.size,selectedV23:newSet.size,unchanged:selected.filter(r=>oldSet.has(r.originalBeatIndex)).length,v22Only:old.rows.filter(r=>r.selected&&!newSet.has(r.originalBeatIndex)).map(r=>r.originalBeatIndex),v23Only:selected.filter(r=>!oldSet.has(r.originalBeatIndex)).map(r=>r.originalBeatIndex),meanSelectedSalience:mean(selected.map(r=>r.actionSalience.total)),meanSkippedSalience:mean(skipped.map(r=>r.actionSalience.total)),meanSelectedV22Salience:mean(old.rows.filter(r=>r.selected).map(r=>r.actionSalience.total)),meanSelectedLocalRank:mean(selected.map(r=>r.localPreference.rank)),inversionsV22:before,inversionsV23:after,priorInversionsCorrected:before.records.filter(r=>newSet.has(r.skippedIndex)&&!newSet.has(r.selectedIndex)).length,priorInversionsResolved:before.records.filter(r=>!after.records.some(a=>a.selectedIndex===r.selectedIndex&&a.skippedIndex===r.skippedIndex)).length,continuityReplacements:selected.filter(r=>r.continuityReplacement).map(r=>r.continuityReplacement),highSalienceMissed:skipped.filter(r=>r.actionSalience.total>=.5).map(r=>({index:r.originalBeatIndex,time:r.targetTime,salience:r.actionSalience.total,reason:r.skippedReason})),weakChoicesRetained:selected.filter(r=>r.actionSalience.total<.2).map(r=>({index:r.originalBeatIndex,time:r.targetTime,reason:r.selectionReason})),neighborhoodV22:neighborhoodDiagnostics(old),neighborhoodV23:neighborhoodDiagnostics(now),challengeV22:metrics(old),challengeV23:metrics(now),ending:now.ending,visualIdentity:V.resolve(now.m)};
}
if(require.main===module){const x={schema:'pulse-tap-v23-comparison',method:'Inversion: salience loss >=.025, skipped beat within +/-2 indices, same four-beat quota window and stage, replaceable without illegal time, <.18s interval or burst violation. Tutorial/landing excluded. Objective values are diagnostics, not subjective correctness. Travel model 375x667 CSS pixels, no insets.',tracks:{alldat:compare('alldat'),cvb:compare('cvb')}};fs.writeFileSync(__dirname+'/PULSE_TAP_V23_COMPARISON.json',JSON.stringify(x,null,2)+'\n');console.log(JSON.stringify(Object.fromEntries(Object.entries(x.tracks).map(([k,v])=>[k,{count:v.selectedV23,inversions:[v.inversionsV22.count,v.inversionsV23.count],stages:v.challengeV23.map(s=>({stage:s.stage,n:s.targets,rate:s.targetsPerSecond,runs:s.runHistogram,travel:s.travelPixels.mean,recovery:s.recoveryGapSeconds.mean}))}]))));}
module.exports={context,metrics,compare,distribution};
