const fs=require('node:fs'),T=require('./timing.js'),D=require('./difficulty.js'),B=require('./test-baseline-v21.cjs'),E=require('./ending.js'),A=require('./action.js');
function compare(name){
 const m=require(`./${name}-analyzer-test.json`),e=require(`./${name}-action-evidence-v22.json`),ending=E.detect(m),times=T.createTiming(m).times,energy=t=>T.energyAt(m,t,m.songLength);
 A.validate(e,times,m.songLength);
 const rows=A.plan(times,ending.playableEndTime,m,e,D,energy,ending.releaseGap),old=B.select(times,ending.playableEndTime,energy,ending.releaseGap),selected=rows.filter(r=>r.selected),skipped=rows.filter(r=>!r.selected&&r.targetTime<ending.playableEndTime);
 const oldSet=new Set(old.map(r=>r.originalBeatIndex)),newSet=new Set(selected.map(r=>r.originalBeatIndex));
 const avg=rs=>rs.length?rs.reduce((a,b)=>a+b.actionSalience.total,0)/rs.length:null;
 const strong=r=>r.actionSalience.total>=.50,weak=r=>r.actionSalience.total<.20;
 const oldLanding=old.filter(r=>r.name==='landing').map(r=>r.targetTime),newLanding=selected.filter(r=>r.name==='landing').map(r=>r.targetTime);
 const stageCounts=D.stages.map(s=>{const r=selected.filter(r=>r.name===s.name);const spec=D.profile(r[0]?.targetTime??0,ending.playableEndTime);return {stage:s.name,targets:r.length,targetsPerSecond:r.length/((spec.end-spec.start)*ending.playableEndTime),window:spec.window,radius:spec.radius,travel:spec.travel};});
 return {sourceCandidates:times.length,selectedV21:old.length,selectedV22:selected.length,unchanged:selected.filter(r=>oldSet.has(r.originalBeatIndex)).length,v21Only:old.filter(r=>!newSet.has(r.originalBeatIndex)).map(r=>({index:r.originalBeatIndex,time:r.targetTime})),v22Only:selected.filter(r=>!oldSet.has(r.originalBeatIndex)).map(r=>({index:r.originalBeatIndex,time:r.targetTime,reason:r.selectionReason})),averageSalienceSelected:avg(selected),averageSalienceSkipped:avg(skipped),averageSalienceV21:avg(rows.filter(r=>oldSet.has(r.originalBeatIndex))),selectedNearLandmarks:selected.filter(r=>r.actionSalience.nearestLandmark?.distance<=.5).length,landmarkNeighborhoodSeconds:.5,strongEvidenceThreshold:.50,strongEvidenceMissed:skipped.filter(strong).map(r=>({index:r.originalBeatIndex,time:r.targetTime,salience:r.actionSalience.total,reason:r.skippedReason})),weakThreshold:.20,weakContinuityRetained:selected.filter(r=>weak(r)&&r.selectionReason!=='salience').map(r=>({index:r.originalBeatIndex,time:r.targetTime,reason:r.selectionReason})),weakSalienceSelected:selected.filter(r=>weak(r)&&r.selectionReason==='salience').length,landingPreserved:JSON.stringify(oldLanding)===JSON.stringify(newLanding),landingTargets:newLanding,ending,stageCounts,sourceTimestampsChanged:false};
}
if(require.main===module){const result={schema:'pulse-tap-v22-selection-comparison',method:'Local four-beat quota windows; all timestamps frozen. Strong/weak cutoffs are diagnostic definitions, not musical truth. Means across stages are confounded by earlier ramp. Salience does not prove fun.',tracks:{alldat:compare('alldat'),cvb:compare('cvb')}};fs.writeFileSync(require('node:path').join(__dirname,'PULSE_TAP_V22_COMPARISON.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(Object.fromEntries(Object.entries(result.tracks).map(([k,v])=>[k,{source:v.sourceCandidates,v21:v.selectedV21,v22:v.selectedV22,unchanged:v.unchanged,oldOnly:v.v21Only.length,newOnly:v.v22Only.length,selectedSalience:v.averageSalienceSelected,skippedSalience:v.averageSalienceSkipped,strongMissed:v.strongEvidenceMissed.length,weakRetained:v.weakContinuityRetained.length,landing:v.landingPreserved,stages:v.stageCounts}]))));}
module.exports={compare};
