from pathlib import Path
import json,csv,hashlib,subprocess,collections,shutil,sys
w=Path(sys.argv[1]).resolve() if len(sys.argv)>1 else Path(__file__).resolve().parent;repo=w/'trackcade-test';base=repo/'research/semantic-external-holdout-v1';out=w/'v9-reclassification-forensics-v1'
load=lambda p:json.loads(p.read_text(encoding='utf-8'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
d=load(out/'STAGE1_V9_RECLASSIFICATION_FORENSICS_V1.json');features=load(out/'prelabel-feature-comparison.json');summary=d['summary']
notes={
 (6,32):('The existing samples rise 0.5750→0.8639 between 29.410 and 29.964s, before the 30.494s baseline anchor. V9 retains Energy at that exact anchor as well as the nearer Peak at 33.306s.','Sampled rise present; no nearby onset source tag or direct concentrated attack measurement.'),
 (10,100):('Samples rise 0.2072→0.7398 between 98.736 and 99.369s, then 0.8395 at 100.002s. V9 explicitly describes a concentrated sampled rise already preceding the same 99.803s anchor.','Rapid adjacent sampled rise present; its acoustic attack and exact impact onset remain unmeasured.'),
 (12,55):('Samples are 0.3885 at 53.891s, 0.6764 at 54.789s and 0.9816 at 55.688s. Adjacent transition/boundary anchors differ by 0.001s; V9 uses the boundary.','Sampled multi-point increase present; transition tag does not prove a concentrated onset.'),
 (12,158):('Samples are 0.4307 at 158.081s, 0.6610 at 158.979s, and 0.7248 at 159.877s. An existing onset-tagged anchor occurs at 159.057s. V9 moves from baseline anchor 126 to adjacent boundary anchor 127 (+0.012s).','Nearby onset tag and sampled increase present; tag salience 0.6750/confidence 0.6892 are not acoustic impact proof.'),
 (26,109):('Samples rise 0.5891→0.9320 from 106.894 to 108.443s and remain high. V9 retains Energy at the exact 108.786s baseline anchor.','Strong sampled rise precedes anchor; no nearby onset source tag or attack measurement.'),
 (26,244):('Samples rise from 0.5852 at 241.673s to 0.8611 at 243.222s and 0.9596 at 244.771s. V9 retains Energy at the exact 242.849s baseline anchor.','Rise across spaced samples present; concentration and acoustic impact unresolved.'),
 (28,90):('Samples rise 0.3581→0.8492 from 87.914 to 89.430s, followed by 0.9656 at 90.946s. Onset-tagged anchor 72 is at 88.746s; V9 uses transition anchor 73 (89.098s), adjacent to baseline boundary anchor 74 (89.102s).','Nearby onset tag and sampled rise present; tag salience 0.6602/confidence 0.6940 do not prove impact morphology.'),
 (41,224):('Samples are already elevated: 0.7824 at 221.262s, 0.7233 at 222.595s, 0.9087 at 223.928s and 0.9150 at 225.261s. No V9 event or candidate assessment is within ±5s. Nearest event is Section at 213.521s.','Modest sampled rise within an already energetic passage; no local boundary or onset tag within the inspected windows. No frozen explanation for omission.'),
 (45,74):('Samples rise 0.4720→0.7651→0.8690 at 72.707/74.053/75.399s. V9 uses the adjacent boundary anchor 43 (73.885s) rather than baseline transition anchor 42 (73.860s).','Increase spans multiple samples; no nearby onset source tag or direct attack measurement.'),
 (45,132):('Samples rise 0.3380→0.6056→0.9964 at 130.602/131.949/133.295s, reaching 1.0 at 134.642s. V9 uses boundary anchor 92 (133.426s); baseline used beat anchor 91 (132.958s). A Peak at 133.495s is also within ±2s.','Broad sampled rise already reaches high level before V9 boundary; no nearby onset source tag or direct attack measurement.')}
for r in d['lostBaselineTruePositives']:
 text,onset=notes[r['ordinal'],r['referenceTimestamp']]
 r['qualitativeEvidenceReview']={'frozenPacketObservations':text,'concentratedOnsetEvidenceAssessment':onset,'directImpactGroundingExplanationPresent':bool(r['v9CandidateAssessmentsWithin5']),'literalDropRejectionStatement':False,'impactBasedDemotionInference':r['within2'],'demotionInferenceLimit':'Frozen non-Drop kind plus weak/unclear impact assessment and explicit lack-of-impact rationale support an interpretation; no cross-run causal identity or hidden model reasoning established.','gameplayMomentAssessment':'Expert-reference proximity retained as an eligible semantic candidate; player interaction suitability untested.' if r['within2'] else 'No semantic event within ±5s; gameplay moment coverage missing under this descriptive rule.','waveformOrListeningEvidenceAvailable':False}
 same=[e for e in d['allV9SemanticEvents'] if e['ordinal']==r['ordinal'] and e['anchor']['index']==r['baselineEvent']['anchor']['index']]
 r['v9EventsAtExactBaselineAnchor']=same
 for key in ['baselineTruePositiveTransitions']:
  # Keep the detailed packet observations once, in focused lost-TP records.
  for generic in d[key]:
   if generic['ordinal']==r['ordinal'] and generic['referenceIndex']==r['referenceIndex']:generic['focusedLostTPRecord']={'ordinal':r['ordinal'],'referenceIndex':r['referenceIndex']}
for r in d['baselineFalsePositiveTransitions']:
 r['v9AssessmentsWithin5']=r['v9CandidateAssessmentsWithin5']
d['prelabelFeatureComparison']=features
d['qualitativeComparison']={'cleanSeparatingEvidenceFound':False,'observation':'Lost TPs and eliminated FPs both show prepared, sustained energy increases, weak/unclear V9 impact assessments and rationales that coarse samples or an adjacent transition do not establish impact at the exact anchor. Some eliminated FPs have weak preparation/persistence or brief recovery, but most have clear preparation and clear sustained stronger passage just like lost TPs.','evidenceExamples':[{'group':'lost_TP','ordinal':10,'timestamp':99.803,'observation':'V9 acknowledges a concentrated sampled rise immediately before the same anchor but leaves impact unclear.'},{'group':'eliminated_FP','ordinal':1,'timestamp':149.674,'observation':'Zero-reference track: samples 0.3993 at 148.200s→0.9763 at 149.682s, an onset tag, clear preparation/persistence; V9 leaves impact unclear and retains Energy.'},{'group':'eliminated_FP','ordinal':20,'timestamp':290.1,'observation':'Samples 0.3996→0.9255 adjacent to boundary, nearby onset tag, clear preparation/persistence; V9 impact unclear.'},{'group':'eliminated_FP','ordinal':44,'timestamp':368.791,'observation':'Weak preparation; incoming section lower on average; V9 sustainedStrongerPassage absent. A narrower, genuinely observed distinction for this case, not a rule separating all FPs.'},{'group':'eliminated_FP','ordinal':32,'timestamp':64.58,'observation':'V9 says stronger level lasts only briefly; preparation clear and sustainedStrongerPassage weak. This differs from the nine assessed lost TPs, but is a small subset.'}],'limits':'No listening/waveform inspection; expert labels only cover Drop timestamps. Frozen rationales are claims to compare with frozen samples, not new acoustic measurements. No deterministic classifier/threshold fitted.'}
d['conclusions']={'reclassificationVsDisappearance':'Mostly semantic relabeling for lost baseline TPs and eliminated baseline FPs; timing/coverage remain limitations across all references.','lostBaselineTPsWithin2':9,'lostBaselineTPsWithin5':9,'lostNearestKindsAt2':{'energy':7,'peak':1,'section':1,'other':0},'lostAbsentWithin5':1,'eliminatedFPsWithin2':47,'eliminatedFPsWithin5':48,'eliminatedFPsAbsentWithin5':2,'gameplayReadiness':'Evidence supports preserving non-Drop events as gameplay candidates and makes loss-of-moments less concerning for the ten lost TPs. It does not establish gameplay readiness: only 26/46 expert Drop references have any event within ±2s, mapping/playtesting are absent, and Drop preregistration still fails.','mainIssue':'For incremental baseline TP loss: semantic classification (9/10 retain moment). Across all 46 references: mixture of classification, timing (13 reference moments only at 2–5s), and event coverage (7 absent within ±5s).','recommendedDevelopmentHypothesis':{'id':'H1','status':'label-informed-unimplemented','text':'Separate anchor-timing uncertainty from musical impact absence in grounded semantic judgments: prepared, sustained transitions with a nearby sampled rise may be conservatively demoted because the frozen anchor does not coincide exactly with an independently resolved attack. A future development study could test whether evaluating existing local temporal evidence jointly preserves true Drops while retaining resistance to ordinary re-entry overcalling.','support':'Nine lost baseline TPs retained as non-Drops; all nine nearby V9 assessments cite weak/unclear impact despite sustained stronger passage; several sampled rises precede or straddle the chosen anchor.','counterevidence':'Eliminated FPs frequently show the same evidence. No clean separating rule is established; no predicted improvement, new threshold, or unseen validation claim.','implemented':False},'alternativeHypotheses':[],'overfitCaution':'Stage1 development labels inform this hypothesis. Repeated Stage1 tuning increases overfit risk. Terminal holdout remains untouched; no preparation or claim of unseen validation.'}
# Remove repeated deep packet reviews from generic TP rows; retain full focused records.
d['baselineTruePositiveTransitions']=[{k:v for k,v in r.items() if k not in ['packetObservationsAtBaselineAnchor','packetObservationsAtNearestV9EventAnchor','qualitativeEvidenceReview','v9CandidateAssessmentsWithin5','v9EventsAtExactBaselineAnchor']} for r in d['baselineTruePositiveTransitions']]
(out/'STAGE1_V9_RECLASSIFICATION_FORENSICS_V1.json').write_bytes((json.dumps(d,separators=(',',':'))+'\n').encode())
def text(v):return '' if v is None else str(v)
def num(v):return '' if v is None else f'{v:.3f}'
def mdtable(headers,rows):return '| '+' | '.join(headers)+' |\n| '+' | '.join(['---']*len(headers))+' |\n'+''.join('| '+' | '.join(str(v).replace('|','\\|').replace('\n',' ') for v in row)+' |\n' for row in rows)
parts=['# Stage1 V9 reclassification forensics V1\n\nProvider-free development analysis of the **V7/V8 accepted50 baseline** (ordinals 1–3 V7; 4–50 V8) against frozen V9. Source HEAD `'+d['sources']['startCommit']+'`. Predictions and all RAW scores remain immutable. No new Drop scoring pass, model execution, semantic reinterpretation, or gameplay mapping is performed.\n\n**Main finding:** nine of the ten baseline Drop TPs lost by V9 still have a semantic event within ±2s (and ±5s). Fifty baseline FPs lose their nearby Drop label; 47 retain a non-Drop event within ±2s and 48 within ±5s. The incremental recall loss mostly concerns semantic labeling. Across all expert references, candidate timing and coverage also remain incomplete.\n']
parts+=['## Method and evidence limits\n\nFrozen ±2s `matchedPairs` and unmatched indices supply the original TP/FP/FN membership; the matcher is not rerun. Every V9 event time resolves its unchanged object evidence anchor to the shared frozen packet. Baseline/V9 proposal hashes and packet hashes are checked for all 50 tracks. Only the previously isolated Stage1 reference excerpt is used, SHA-256 `'+d['sources']['referenceSha256']+'`; its baseline isolation proof records zero terminal bytes.\n\nFor each query, nearest means minimum absolute distance, then earlier timestamp, then original event-array index. Equal-distance ties and all nearby kinds are retained in JSON/CSV. An event can serve more than one query. This proximity correspondence is not one-to-one matching and does not prove cross-run causal identity, semantic correctness, or player interaction quality. Windows are inclusive and use the existing 1e-12 timing tolerance. Other kinds would be included, but V9 contains only Drop, Peak, Energy, and Section.\n\n“Correct moment retained” in the focused categories means temporal correspondence to an expert reference. It does not adjudicate a new semantic label after seeing labels. Priority, salience, confidence and onset source codes are frozen Analyzer-derived features, not Drop probability or proof of a waveform impact. No audio, new attack measurements, interpolated energy, or label-derived thresholds are introduced.\n']
parts+=['## A. Baseline 21 TP transitions\n\nExact frozen-reference overlap: 11 retained V9 Drop TPs, 10 lost, and zero new V9 TPs among the baseline’s 25 missed references. Thus the requested ten-event lost set is confirmed rather than inferred from net counts.\n\n'+mdtable(['Transition','±2s primary','±5s sensitivity'],[['Retained RAW Drop TP',11,11],['Nearest Peak',1,1],['Nearest Energy',7,7],['Nearest Section',1,1],['Other semantic event',0,0],['Event only within 2–5s',0,'included above'],['Absent within ±5s',1,1]])+'\nAll 21 event rows, original matched timestamps/errors and V9 descriptions appear in the event CSV and forensic JSON.\n']
parts+=['## B. Baseline 60 FP transitions\n\n'+mdtable(['Nearest V9 kind/correspondence','±2s','±5s'],[['Drop',10,10],['Peak',0,0],['Energy',28,28],['Section',19,20],['Other',0,0],['No event in the specified window',3,2]])+'\nAt ±2s, the three without event comprise one shifted Section at 3.211s and two absent within ±5s. Each of the 60 original FP timestamps and its nearest-reference distance (null for zero-reference tracks) is preserved in the CSV. A nearby V9 Drop is not automatically called an FP by this proximity analysis; its frozen RAW status is separate.\n']
parts+=['## C. All 35 V9 Drop FNs\n\n'+mdtable(['Nearest semantic event','±2s','±5s'],[['Peak',1,2],['Energy',11,17],['Section',3,9],['Other including Drop',0,0],['Event only within 2–5s',13,'included above'],['Absent within ±5s',7,7],['Any-event coverage total',15,28]])+'\nThe ten lost baseline TPs contribute nine covered references and one absent reference. The 25 references already missed by the baseline contribute six covered within ±2s, 13 additional covered only at 2–5s, and six absent within ±5s. None becomes a V9 RAW Drop TP. The FN CSV reports immutable baseline FN membership separately from proximity to any unmatched baseline Drop; these groups are not conflated.\n']
lost=d['lostBaselineTruePositives']
parts+=['## D. Focused ten lost baseline TPs\n\n'+mdtable(['Ordinal / stem','Reference s','Baseline Drop s (error)','Nearest V9 event s','Kind','Distance s','Outcome'],[[f"{r['ordinal']} / {r['stem']}",num(r['referenceTimestamp']),f"{num(r['baselineTimestamp'])} ({num(r['baselineTimingErrorSeconds'])})",num(r['v9Timestamp']),r['v9Kind'],num(r['v9DistanceSeconds']),'Retained moment within ±2s' if r['within2'] else 'Absent within ±5s'] for r in lost])+'\n**Nearest-kind caveat:** ordinal 6 also retains Energy at the exact baseline anchor 30.494s, while a Peak at 33.306s lies closer to the 32s reference. Its headline bin is Peak under the specified nearest-reference query, not evidence of a literal Drop→Peak rewrite. Ordinal 45 at 132s also has a nearby Peak, but the Energy event is closest.\n']
for r in lost:
 parts.append(f"### Ordinal {r['ordinal']} / {r['stem']}, reference {r['referenceTimestamp']:.3f}s\n\nBaseline: {r['baselineRationale']}\n\nV9 nearest event: {r['v9NearestEvent'].get('rationale','No rationale')}\n\nFrozen evidence: {r['qualitativeEvidenceReview']['frozenPacketObservations']}\n\nConcentrated-onset evidence: {r['qualitativeEvidenceReview']['concentratedOnsetEvidenceAssessment']}\n\n")
 assessments=r['v9CandidateAssessmentsWithin5']
 if assessments:
  a=assessments[0];parts.append(f"V9 assessment at anchor {a['anchor']['index']}: decisiveImpact={a['decisiveImpact']}, preparation={a['preparation']}, sustainedStrongerPassage={a['sustainedStrongerPassage']}, role={a['semanticRole']}. Rationale: {a['rationale']}\n\nThe frozen output explicitly says impact at the anchor is unsubstantiated; together with the non-Drop event this supports an impact-grounding demotion interpretation. It does not literally state a cross-version rejection of the baseline Drop, and hidden model reasoning is unavailable. The nearby semantic event remains eligible for gameplay mapping; interaction suitability is untested.\n\n")
 else:parts.append('No candidate assessment within ±5s explains the omission. Impact-grounding rejection cannot be inferred for this case. This is a semantic-event coverage loss around the reference; the frozen samples cannot establish the acoustic cause.\n\n')
parts+=['## E. The 50 eliminated baseline FPs\n\nFor each original FP, “eliminated as Drop” means no V9 Drop within ±2s of that baseline timestamp; ±5s repeats the check. Here that independently identified set is 50 in both windows. Of those 50, 28 become nearest Energy and 19 nearest Section within ±2s; one more Section appears at 3.211s; two have no event within ±5s. The retained ten nearby Drop events are ten distinct V9 event indices and retain their frozen FP identity (verified independently).\n\n'+mdtable(['Existing pre-label feature / nearest assessment','Lost TPs (10)','Eliminated FPs (50)'],[['Assessment within ±5s','9','49'],['Impact weak / unclear / absent / missing','5 / 4 / 0 / 1','31 / 15 / 3 / 1'],['Preparation clear / weak / missing','8 / 1 / 1','45 / 4 / 1'],['Sustained stronger passage clear','9','45'],['Existing onset source tag within ±2s of baseline anchor','2','18'],['Existing section boundary within ±5s','9','50']])+'\nThis table counts existing categorical judgments and source tags, not new acoustic measurements. Assessments are selected by nearest anchor to the original baseline timestamp within ±5s; all exact rationales remain in JSON.\n\n**No clean qualitative separator is established.** Lost TPs and most eliminated FPs both have clear preparation, persistent stronger energy and weak/unclear impact assessments. Their V9 rationales frequently invoke the same uncertainty: a sampled rise already precedes the chosen anchor, straddles it, or does not isolate an attack at that exact point.\n\nExamples make the overlap concrete. Lost TP ordinal 10 has 0.2072→0.7398 across adjacent samples before the anchor, and V9 calls the sampled rise concentrated but the impact unresolved. Eliminated FP ordinal 1 on a zero-reference track has 0.3993→0.9763 across adjacent samples, an existing onset tag, clear preparation and persistence, yet the same unclear-impact judgment. Eliminated FP ordinal 20 has 0.3996→0.9255 around a nearby onset tag and again clear preparation/persistence. Hence an adjacent jump, preparation, persistence, or onset tag alone cannot be offered as a separating rule from these data.\n\nSome eliminated FPs have genuinely different frozen evidence: ordinal 44 at 368.791s has weak preparation and no sustained stronger passage; ordinal 32 at 64.580s has weak persistence and only a brief stronger level; ordinal 4 at 168.007s describes a recovery whose high point falls back and whose adjacent sections have similar energy. These observations justify case-specific caution but cover only a subset, not the majority. No threshold or classifier is fitted. A rationale is an output claim, and cited observations can refer to a broader neighborhood than the baseline anchor; the exact packet samples are included so that such claims remain inspectable.\n\nEvery eliminated FP’s frozen assessments, rationale, section-boundary context and anchor-local samples appear in JSON; CSV retains the correspondence rows.\n']
parts+=['## F. Semantic-event coverage around expert Drop references\n\n**Descriptive gameplay coverage only; these are not Drop true positives.**\n\n'+mdtable(['Tolerance','Covered references / 46','Coverage','Nearest Drop','Nearest Peak','Nearest Energy','Nearest Section'],[[f'±{t}s',f"{summary['all46ReferenceCoverage'][str(t)]['covered']} / 46",f"{summary['all46ReferenceCoverage'][str(t)]['covered']/46*100:.2f}%",*[summary['all46ReferenceCoverage'][str(t)]['nearestEventKindCountsAmongCovered'].get(k,0) for k in ['drop','peak','energy','section']]] for t in [1,2,5]])+'\nNearest-kind bins are exclusive. Nonexclusive reference-kind presence is also recorded: at ±2s, references have nearby Drop/Peak/Energy/Section in 11/2/12/3 cases; at ±5s in 11/7/18/11 cases. A reference can have several nearby kinds.\n\n'+mdtable(['V9 kind','Total events','Events within ±2s of any reference','Events within ±5s'],[[k,summary['v9EventCountsNearReferences'][k]['total'],summary['v9EventCountsNearReferences'][k]['within2'],summary['v9EventCountsNearReferences'][k]['within5']] for k in ['section','peak','energy','drop']])+'\nThe event-count table counts each V9 event once, regardless of how many references it neighbors; it differs from counting covered references. Section, Peak and Energy events remain potentially useful for chorus entrances, re-entries, energy lifts, boundaries, peaks and breakdown endings. None is discarded or converted to Drop.\n']
parts+=['## G. Fifty-track view\n\nFull IDs are in `STAGE1_V9_TRACK_COVERAGE_V1.csv`. Baseline columns always mean V7/V8 accepted50 baseline.\n\n'+mdtable(['Ord / stem','Refs','Baseline Drops','Baseline TP/FP/FN','V9 Drops','V9 TP/FP/FN','Peak','Energy','Section','Any-event refs ±2 / ±5'],[[f"{r['ordinal']} / {r['stem']}",r['referenceDropCount'],r['baselineDropCount'],f"{r['baselineTP']}/{r['baselineFP']}/{r['baselineFN']}",r['v9DropCount'],f"{r['v9TP']}/{r['v9FP']}/{r['v9FN']}",r['v9PeakCount'],r['v9EnergyCount'],r['v9SectionCount'],f"{r['referencesWithAnyV9EventWithin2']} / {r['referencesWithAnyV9EventWithin5']}" ] for r in d['trackCoverage']])+'\nAll 50 tracks have semantic events. Missing reference-local coverage is not an entire-track disappearance. Seven references lack any event within ±5s: ordinal 7 at 150s (nearest distance 5.151s), 8 at 200s (34.524s), 23 at 68s (5.381s), 28 at 178s (38.598s), 29 at 293s (24.500s), 41 at 224s (10.479s), and 42 at 159s (10.082s). The first and third are near the window edge; the larger distances are substantive reference-local omissions under this descriptive test.\n']
parts+=['## H. Conclusions and one unimplemented development hypothesis\n\n1. **Reclassification predominates in incremental loss:** nine of ten lost baseline TPs retain a nearby semantic event. Only one is absent within ±5s.\n2. **Lost TP coverage:** nine within ±2s and nine within ±5s.\n3. **Absorbing nearest kinds:** seven Energy, one Peak, one Section, zero other. Exact-anchor correspondence can differ from nearest-reference kind, as ordinal 6 illustrates.\n4. **Eliminated FPs:** 47/50 retain nearby non-Drops at ±2s, 48/50 at ±5s; two disappear within ±5s and one shifts by 3.211s.\n5. **Gameplay usefulness:** the preserved moments support keeping non-Drops eligible for separate action mapping. This improves the assessment of candidate preservation, but does not establish gameplay readiness or successful gameplay interactions. Only 26/46 expert references have any event within ±2s. The failed Drop-retention preregistration remains failed.\n6. **Main issue:** semantic classification dominates the ten incremental TP losses. For the full reference set, the issue is a mixture: classification, 13 event correspondences only at 2–5s, and seven without coverage within ±5s.\n7. **Recommended H1 (label-informed, not implemented):** '+d['conclusions']['recommendedDevelopmentHypothesis']['text']+'\n\nThis is a falsifiable development hypothesis, not an established correction. The same evidence motifs occur among many eliminated FPs, so there is no demonstrated rule that would recover the lost TPs without reviving overcalling. No new prompt, model, treatment, threshold, deterministic post-filter, or V10 is created. Stage1 labels inform this hypothesis; repeated Stage1 tuning increases overfit risk. These data provide no unseen validation. Terminal holdout remains untouched, and no terminal preparation occurs.\n\n## Integrity and continuation stop\n\nProvider calls this analysis: **0**; spend: **$0**. Predictions, semantic treatment, scoring contracts and prior RAW records are unchanged. No generation rerun, scoring rerun, Analyzer or compiler invocation, terminal labels or terminal metadata inspection. The complete input hashes/artifact identities and output hashes are pinned in the JSON receipt. Commit/push this provider-free analysis and stop.\n']
(out/'STAGE1_V9_RECLASSIFICATION_REPORT_V1.md').write_bytes(('\n'.join(parts)).encode('utf-8'))
# Focused CSV is a readable companion to the deep JSON record.
with (out/'STAGE1_V9_LOST_TP_FOCUSED_TABLE_V1.csv').open('w',encoding='utf-8',newline='') as f:
 fields=['ordinal','id','stem','referenceTimestamp','baselineTimestamp','baselineTimingErrorSeconds','v9Timestamp','v9Kind','v9DistanceSeconds','within1','within2','within5','focusedClassification','baselineRationale','v9NearestEvent','v9CandidateAssessmentsWithin5','packetObservationsAtBaselineAnchor','packetObservationsAtNearestV9EventAnchor','qualitativeEvidenceReview','v9EventsAtExactBaselineAnchor']
 writer=csv.DictWriter(f,fieldnames=fields,lineterminator='\n');writer.writeheader()
 for r in lost:writer.writerow({k:json.dumps(r[k],separators=(',',':')) if isinstance(r.get(k),(dict,list)) else r.get(k) for k in fields})
print(json.dumps({'forensicBytes':(out/'STAGE1_V9_RECLASSIFICATION_FORENSICS_V1.json').stat().st_size,'reportBytes':(out/'STAGE1_V9_RECLASSIFICATION_REPORT_V1.md').stat().st_size,'hypothesisImplemented':False}))
