"""Readable listening report; raw research arrays are not a prerequisite."""
from pathlib import Path
import json, hashlib
ROOT=Path(__file__).resolve().parent
def load(name):return json.loads((ROOT/'results'/name).read_text(encoding='utf-8'))
data={n:{'events':load(n+'-events.json'),'families':load(n+'-motifs.json')['families'],'summary':load(n+'-summary.json'),'anchors':load(n+'-anchors.json')} for n in ['alldat','cvb']}
for d in data.values():
    ids={i for f in d['families'] for o in f['occurrences'] for i in o['eventIds']}
    d['events']=[{k:e[k] for k in ['id','time','strength','timingConfidence','timingUncertaintySeconds','strictGameplayCandidate']} for e in d['events'] if e['id'] in ids]
    for f in d['families']:
        f['canonicalPattern']={k:f['canonicalPattern'][k] for k in ['normalizedIntervals','strengthContour']}
html='''<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Trackcade — recurring-figure research</title>
<style>body{font:16px system-ui;margin:auto;max-width:1100px;padding:24px;background:#111726;color:#eef2f8}button,select{font:inherit;padding:10px;border:1px solid #7b89a6;border-radius:6px;background:#22314b;color:white;cursor:pointer}button:focus{outline:3px solid #72e7c3}p{line-height:1.5}.warning{padding:18px;background:#513321;border-radius:8px}article{background:#1b2539;padding:18px;margin:18px 0;border-radius:8px}.stats{color:#b4e9de}table{border-collapse:collapse;width:100%;font-size:14px}td,th{text-align:left;padding:8px;border-bottom:1px solid #354460}.scroll{overflow:auto}svg{width:100%;height:100px;background:#121c30}audio{width:100%;margin:12px 0}.small{color:#b1bed3;font-size:14px}summary{cursor:pointer;padding:10px}.event{color:#8febcd}code{font-size:13px}</style>
<h1>Recurring musical figures: research review</h1>
<p class="warning"><b>Result D — not ready for gameplay integration.</b> Both songs produce recurring candidates, but shuffled controls score as strongly. These are listening hypotheses, not confirmed musical motifs. Timing gates are provisional; production-validated event count is zero. Pulse Tap v2.3 remains unchanged.</p>
<p>Select a song, inspect its families, and listen to repeated occurrences. No manual timestamps were supplied to the detector. Listening here is post-analysis review, not training data.</p>
<label>Song <select id="track"><option value="alldat">ALLDAT</option><option value="cvb">CVB G.E.M.F.</option></select></label>
<audio id="audio" controls preload="none"></audio><p id="now" aria-live="polite">Choose an occurrence to listen.</p><p id="stats"></p>
<p class="small">Green ticks pass the provisional DSP timing gate; amber ticks do not. All source identities are UNKNOWN. “Confidence” below is mean heuristic similarity, not a calibrated probability. Near-beat comparison uses ±20ms; outside that threshold does not prove a distinct off-beat musical intention.</p><div id="families"></div>
<script>const DATA=__DATA__;const $=id=>document.getElementById(id);let stopAt=null;
function listen(start,end){const a=$('audio');a.currentTime=Math.max(0,start-.3);stopAt=end+.4;a.play().catch(e=>{$('now').textContent='Audio unavailable: '+e.message});$('now').textContent='Listening '+start.toFixed(3)+'–'+end.toFixed(3)+' seconds';}
$('audio').addEventListener('timeupdate',()=>{if(stopAt!==null&&$('audio').currentTime>=stopAt){$('audio').pause();stopAt=null}});
function render(){const name=$('track').value,d=DATA[name],s=d.summary;stopAt=null;$('audio').pause();$('audio').src='../../'+(name==='alldat'?'ALLDAT_ruffmix.mp3':'cvb-gemf-sample.mp3');
 $('stats').textContent=s.eventCount+' detected events · '+s.provisionalTimingGateCount+' provisional timing-gate passes · '+s.familyCount+' candidate families · 0 approved anchors · shuffled control top prominence '+s.descriptorShuffleNull.topProminence.toFixed(3);
 $('families').replaceChildren();for(const f of d.families){const article=document.createElement('article'),coverage=d.anchors.coverage.find(c=>c.family===f.id),title=document.createElement('h2');title.textContent=f.eventCount+'-event candidate · '+f.id;article.append(title);
 const p=document.createElement('p');p.className='stats';p.textContent=f.occurrenceCount+' recurrences · similarity '+f.recurrenceConfidence.toFixed(3)+' · prominence '+f.motifProminence.toFixed(3)+' · span '+(100*f.songCoverage).toFixed(1)+'% of song';article.append(p);
 const q=document.createElement('p');q.textContent='Relative gaps: '+f.canonicalPattern.normalizedIntervals.map(x=>x.toFixed(2)).join(' → ')+' · relative attacks: '+f.canonicalPattern.strengthContour.map(x=>x.toFixed(2)).join(' → ');article.append(q);
 const info=document.createElement('p');info.className='small';info.textContent='All-event timing-gate occurrences: '+f.timingGateOccurrenceCount+'. Current v2.3: '+coverage.v23Partial+' partial, '+coverage.v23Full+' full. Proposed anchor coverage: 0% (fail-closed). Chroma is a mixed-spectrum descriptor; no note/instrument/vocal identity is claimed.';article.append(info);
 const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Inspect and listen to all '+f.occurrenceCount+' occurrences';details.append(summary);const wrap=document.createElement('div');wrap.className='scroll';const table=document.createElement('table');table.innerHTML='<thead><tr><th>Listen</th><th>Events / spacing (seconds)</th><th>Similarity / timing</th><th>Beat offsets (ms)</th></tr></thead>';const body=document.createElement('tbody');
 for(const o of f.occurrences){const tr=document.createElement('tr'),td=document.createElement('td'),button=document.createElement('button');button.textContent='▶ '+o.startTime.toFixed(2)+'s';button.onclick=()=>listen(o.startTime,o.endTime);td.append(button);tr.append(td);
 const time=document.createElement('td');time.textContent=o.eventTimes.map(x=>x.toFixed(3)).join(' · ');const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 500 100');o.eventIds.forEach((id,i)=>{const e=d.events.find(e=>e.id===id),line=document.createElementNS(svg.namespaceURI,'line'),x=25+(o.eventTimes[i]-o.startTime)/Math.max(.1,o.endTime-o.startTime)*450;line.setAttribute('x1',x);line.setAttribute('x2',x);line.setAttribute('y1',85);line.setAttribute('y2',85-65*e.strength);line.setAttribute('stroke',e.strictGameplayCandidate?'#82e2ba':'#ffc572');line.setAttribute('stroke-width',6);const title=document.createElementNS(svg.namespaceURI,'title');title.textContent=e.time+'s; uncertainty '+(e.timingUncertaintySeconds*1000).toFixed(1)+'ms; confidence '+e.timingConfidence;line.append(title);svg.append(line)});time.append(svg);tr.append(time);
 const status=document.createElement('td');status.textContent=o.matchScore.toFixed(3)+' / '+(o.allEventsPassDspTimingGate?'all provisional':'some uncertain');tr.append(status);const off=document.createElement('td');off.textContent=o.beatOffsetsSeconds.map(x=>x===null?'unknown':(x*1000).toFixed(1)).join(' · ');tr.append(off);body.append(tr)}table.append(body);wrap.append(table);details.append(wrap);article.append(details);$('families').append(article)} }
$('track').addEventListener('change',render);render();</script>'''
html=html.replace('__DATA__',json.dumps(data,separators=(',',':')).replace('</','<\\/'))
(ROOT/'REPORT.html').write_bytes(html.encode())
print(json.dumps({'htmlBytes':len(html.encode()),'sha256':hashlib.sha256(html.encode()).hexdigest()}))
