// Design assignment depends only on measured signals; filenames are display metadata.
const fs=require('node:fs'),path=require('node:path'),root=__dirname,brief=require('./brief.json');
function assign(rows){
 const dense=rows.slice().sort((a,b)=>b.measurements.broadAttackDensityPerSecond-a.measurements.broadAttackDensityPerSecond||a.id.localeCompare(b.id))[0];
 const remainder=rows.filter(r=>r!==dense),contrast=remainder.slice().sort((a,b)=>b.measurements.dynamicContrastRatio-a.measurements.dynamicContrastRatio||a.id.localeCompare(b.id))[0];
 return Object.fromEntries(rows.map(r=>[r.id,r===dense?'signal-towers':r===contrast?'hinge-atrium':'ribbon-terraces']));
}
const concepts={
 'ribbon-terraces':{name:'Paint Terraces',environment:'wide suspended terraces over a deep sculpted basin',composition:'horizontal foreground shelves, curved horizon and distant stacked islands',graffiti:'large wrapped wall glyphs, broad brushed ribbons and soft short drips',motion:'slow opposing terrace drift with low-amplitude paint-band breathing',transition:'a painted horizon ribbon travels across the terraces at objective contrast changes',target:'two broad chalk brackets outside the closing ring',impact:'a flattened short paint swipe',energyResponse:'subtle shelf lift and mural brightness; broad movement capped',density:'sparse broad strokes',lighting:'warm beveled upper edges and soft long shadows',mood:'spacious, graphic, grounded',palette:{bg:'#182033',panel:'#263549',primary:'#50d8c9',secondary:'#f08053',gold:'#f9d184',white:'#fff1d6',muted:'#c1c8ce',danger:'#e96662'}},
 'hinge-atrium':{name:'Folded Paint Hall',environment:'a sculpted atrium with oversized hinged panels and open arches',composition:'diagonal foreground wedges, alternating side shutters and a central arch',graffiti:'cutout spray stencils split across hinged surfaces; paint appears as panels open',motion:'slow hinged panel opening, with stronger contrast-driven expansion',transition:'opposed shutters reveal a fresh stencil panel at objective contrast changes',target:'three directional paint wedges around the closing ring',impact:'a small angular stencil stamp',energyResponse:'panel openness follows smoothed energy; contrast changes release one stencil',density:'medium, localized bursts',lighting:'crisp edge highlights and deep cel-shaded recesses',mood:'sculptural, responsive, deliberate',palette:{bg:'#211a34',panel:'#392850',primary:'#b5a0f4',secondary:'#efb553',gold:'#fbe3a1',white:'#fff1d6',muted:'#c9bfd3',danger:'#e96662'}},
 'signal-towers':{name:'Paint Signal Garden',environment:'a stepped field of offset painted monoliths around a clear central lane',composition:'vertical side towers, staggered depth, stepped pedestal floor',graffiti:'vertical sprayed glyph stacks climbing separate tower faces; paint caps glow in sequence',motion:'bounded vertical lifts and slow depth parallax; no constant full-screen flash',transition:'one paint band climbs the tower stack at objective contrast changes',target:'four compact dashed paint caps around the closing ring',impact:'a short upward paint spray',energyResponse:'tower lift and glyph reveal respond to smoothed energy; accents only every fourth pulse',density:'compact repeated vertical marks',lighting:'rim-lit caps with flat dark side planes',mood:'structured, bold, kinetic',palette:{bg:'#182726',panel:'#2a4037',primary:'#b9dc70',secondary:'#61cbd7',gold:'#f4d586',white:'#fff1d6',muted:'#bdccc6',danger:'#e96662'}}
};
function generate(){const rows=['laid-back','wanna-get-lit','need-a-bag'].map(id=>({id,...JSON.parse(fs.readFileSync(path.join(root,'tracks',id+'.json'),'utf8'))})),map=assign(rows);fs.mkdirSync(path.join(root,'visuals'),{recursive:true});for(const row of rows){const style=map[row.id],concept=concepts[style],manifest={schema:'trackcade-private-first-pass-artist-visual-v1',id:row.id,style,originalArtistInput:brief.originalArtistInput,trackcadeInterpretation:brief.trackcadeInterpretation,sharedDNA:brief.sharedDNA,...concept,objectiveInfluence:{selectionRule:style==='signal-towers'?'highest measured broad attack density; most regular pulse strengthens bounded vertical rhythm':style==='hinge-atrium'?'highest dynamic contrast among remaining tracks: revealing panels respond to quiet/busy change':'remaining broad-space interpretation: lower broad attack density, slower pulse and lower contrast than atrium',measurements:row.measurements},sourceIdentity:'UNKNOWN',titleDrivenTheme:false,genreInference:false};fs.writeFileSync(path.join(root,'visuals',row.id+'.json'),JSON.stringify(manifest,null,2)+'\n');row.pulseVisual={palette:concept.palette,themeDirection:concept.environment,backgroundIntensityScale:.6,pulseIntensityScale:.4};row.artistVisual=manifest;delete row.id;fs.writeFileSync(path.join(root,'tracks',manifest.id+'.json'),JSON.stringify(row,null,2)+'\n');}return map;}
if(require.main===module)console.log(generate());module.exports={assign,concepts,generate};
