const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),cp=require('node:child_process'),root=__dirname,repo=path.resolve(root,'..'),ids=['laid-back','wanna-get-lit','need-a-bag'];
const T=require('../pulse-tap/timing.js'),D=require('../pulse-tap/difficulty.js'),E=require('../pulse-tap/ending.js'),A=require('../pulse-tap/action.js'),I=require('../pulse-tap/impact.js'),brief=require('./brief.json'),{assign}=require('./manifests.cjs');
const P=require('./private-plan.js');
let passed=0;const checks=[];function test(name,fn){fn();passed++;checks.push(name);}
const rows=ids.map(id=>({id,...require('./tracks/'+id+'.json')})),visuals=rows.map(r=>r.artistVisual);
test('exact artist vision',()=>assert.equal(brief.originalArtistInput.vision,'Cartoonish Fortnite type vibe.'));
test('exact Must Have',()=>assert.equal(brief.originalArtistInput.mustHave,'graffiti'));
test('exact Must Not Have',()=>assert.equal(brief.originalArtistInput.mustNotHave,'zesty'));
test('ambiguity preserved separately',()=>{assert.equal(brief.trackcadeInterpretation.zesty.originalConstraint,'zesty');assert.match(brief.trackcadeInterpretation.zesty.confidence,/low/)});
test('three independent manifests',()=>assert.equal(new Set(visuals.map(v=>v.style)).size,3));
test('same original input every song',()=>visuals.forEach(v=>assert.deepEqual(v.originalArtistInput,brief.originalArtistInput)));
test('shared artist DNA',()=>visuals.forEach(v=>assert.deepEqual(v.sharedDNA,brief.sharedDNA)));
test('graffiti visible treatments differ',()=>{assert.equal(new Set(visuals.map(v=>v.graffiti)).size,3);visuals.forEach(v=>assert.ok(v.graffiti.length>35))});
test('beyond-color pair differentiation',()=>{for(let i=0;i<3;i++)for(let j=i+1;j<3;j++)assert.ok(['environment','composition','graffiti','motion','transition','target','impact'].filter(k=>visuals[i][k]!==visuals[j][k]).length>=3)});
test('assignment ignores titles',()=>assert.deepEqual(assign(rows),assign(rows.map(r=>({...r,title:'arbitrary filename'})))));
test('assignment uses measured density',()=>{const ranked=rows.slice().sort((a,b)=>b.measurements.broadAttackDensityPerSecond-a.measurements.broadAttackDensityPerSecond);assert.equal(assign(rows)[ranked[0].id],'signal-towers')});
test('no genre inference',()=>visuals.forEach(v=>assert.equal(v.genreInference,false)));
test('no title-literal theme',()=>visuals.forEach(v=>assert.equal(v.titleDrivenTheme,false)));
test('no source identity invention',()=>visuals.forEach(v=>assert.equal(v.sourceIdentity,'UNKNOWN')));
test('no private audio tracked',()=>{const files=cp.execFileSync('git',['ls-files'],{cwd:repo,encoding:'utf8'}).split('\n');rows.forEach(r=>assert.ok(!files.some(p=>path.basename(p)===r.provenance.filename)))});
test('no audio bytes or files in namespace',()=>{function walk(p){for(const e of fs.readdirSync(p,{withFileTypes:true})){const file=path.join(p,e.name);if(e.isDirectory())walk(file);else assert.ok(!/\.(mp3|wav|f32|ogg|m4a)$/i.test(file));}}walk(root);for(const f of ['play.html','preview.html','preview.js'])assert.ok(!fs.readFileSync(path.join(root,f),'utf8').includes('data:audio'))});
test('local audio URLs only',()=>rows.forEach(r=>assert.equal(r.audioUrl,'/audio/'+r.id)));
test('no motif research runtime import',()=>{for(const file of ['play.html','world.js','prepare.py'])assert.ok(!/motif_families|micro-motif-v[12]\/|\/research\//.test(fs.readFileSync(path.join(root,file),'utf8')))});
test('procedural art; no image asset URLs',()=>assert.ok(!/https?:|\.png|\.jpg|\.webp/.test(fs.readFileSync(path.join(root,'world.js'),'utf8'))));
test('CSP local and loopback allowlist',()=>{const s=fs.readFileSync(path.join(root,'serve.cjs'),'utf8');assert.ok(s.includes("'127.0.0.1'"));assert.ok(s.includes("default-src 'self'"));assert.ok(!s.includes('Access-Control-Allow-Origin'))});
test('v2.3 modules referenced unchanged',()=>{const html=fs.readFileSync(path.join(root,'play.html'),'utf8');for(const name of ['timing','difficulty','ending','choice','action','impact'])assert.ok(html.includes('/engine/'+name+'.js'))});
test('PERFECT ring center and precision unchanged',()=>{assert.equal(I.visual(3,3,.6).ringScale,1/1.75);assert.equal(I.judge(3.003,3,.23).timingScore,120);assert.ok(I.judge(3.020,3,.23).timingScore<120);assert.equal(I.judge(3,3,.23).maximumTolerance,.005)});
test('no hand-authored music timestamps',()=>{for(const r of rows){const times=T.createTiming(r).times;const p=r.measurements.estimatedPulseIntervalSeconds;for(let i=1;i<times.length;i++)assert.ok(Math.abs(times[i]-times[i-1]-p)<.000001)}});
test('repeated planning deterministic',()=>rows.forEach(r=>{const end=E.detect(r),f=()=>P.plan(T.createTiming(r).times,end.playableEndTime,r,null,D,t=>T.energyAt(r,t,r.songLength),end.releaseGap);assert.equal(JSON.stringify(f()),JSON.stringify(f()))}));
test('five-second tutorial and relative arc',()=>rows.forEach(r=>{assert.equal(D.profile(4,r.songLength).name,'opening');assert.equal(D.profile(6,r.songLength).name,'build');assert.equal(D.profile(r.songLength*.55,r.songLength).name,'mid-hard-push');assert.equal(D.profile(r.songLength*.85,r.songLength).name,'final-climax')}));
test('climax smaller harder targets',()=>rows.forEach(r=>{const mid=D.profile(.55*r.songLength,r.songLength),final=D.profile(.85*r.songLength,r.songLength);assert.ok(final.radius<mid.radius&&final.window<mid.window&&final.travel>mid.travel)}));
test('release safety and landing',()=>rows.forEach(r=>{const e=E.detect(r),plan=P.plan(T.createTiming(r).times,e.playableEndTime,r,null,D,t=>T.energyAt(r,t,r.songLength),e.releaseGap);assert.ok(plan.filter(p=>p.selected).every(p=>E.targetFits(p.targetTime,p.window,e)));assert.equal(D.profile(e.playableEndTime*.98,e.playableEndTime).name,'landing')}));
test('fixtures V9 research and Pages unchanged',()=>{const changed=cp.execFileSync('git',['diff','--name-only','eb82fd67d49e8bab67415519af576d4aee8d95b2'],{cwd:repo,encoding:'utf8'}).trim().split('\n').filter(Boolean);assert.ok(changed.every(p=>p.startsWith('private-artist-pulse-v1/')))});
test('first pass, no revision workflow',()=>assert.equal(brief.firstPassOnly,true));
test('provider and spend zero',()=>{assert.equal(brief.providerCalls,0);assert.equal(brief.spendUSD,0)});
const engineHashes=Object.fromEntries(['timing.js','difficulty.js','ending.js','choice.js','action.js','visual.js','impact.js'].map(name=>[name,crypto.createHash('sha256').update(fs.readFileSync(path.join(repo,'pulse-tap',name))).digest('hex')]));
fs.writeFileSync(path.join(root,'CONTRACT_VERIFICATION.json'),JSON.stringify({passed,failed:0,checks,engineHashes},null,2)+'\n');console.log(JSON.stringify({passed,failed:0}));
