"""Derived timestamps and scores only; never embeds audio or private filesystem paths."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
def build():
    records=[]
    for path in sorted((ROOT/'results').glob('*.json')):
        r=json.loads(path.read_text(encoding='utf-8'));records.append({k:r[k] for k in ['input','summary','families','nullDistributions']})
    data=json.dumps(records,separators=(',',':'),allow_nan=False).replace('<','\\u003c')
    html='''<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Trackcade Micro-Motif v2 — private review</title>
<style>body{font:16px system-ui;max-width:1050px;margin:auto;padding:20px;background:#101521;color:#e2e9f5}select,button{font:inherit;padding:8px;margin:4px}audio{width:100%}article{padding:12px;margin:16px 0;border:1px solid #586987;border-radius:8px}.muted{color:#b9c4d7}.times{overflow-wrap:anywhere}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:5px;border-bottom:1px solid #455}summary{cursor:pointer}h1{font-size:26px}</style>
<h1>Micro-Motif v2 · local five-song review</h1><p>Research only. Source identity UNKNOWN. No lyrics, reference labels or audio embedded. A repeated phrase is a candidate, not a gameplay approval. Real timestamp error remains unknown.</p>
<select id="track" aria-label="Song"></select><audio id="audio" controls preload="none"></audio><p id="status" class="muted"></p><section id="summary"></section><section id="families"></section><section id="controls"></section>
<script>const records=DATA;const q=s=>document.querySelector(s);const sec=v=>Number(v).toFixed(3);const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
q('#track').innerHTML=records.map((r,i)=>`<option value="${i}">${esc(r.input.filename)}</option>`).join('');
function render(){const r=records[+q('#track').value],s=r.summary;q('#audio').src='/audio/'+r.input.id;q('#status').textContent='Audio resolves from your explicit local input map only. Local playback does not publish it.';q('#summary').innerHTML=`<h2>${esc(r.input.filename)}</h2><p>${s.eventCount} exploratory events · ${s.internallyStableCount} internally stable · ${s.calibrationSupportedStrictCount} strict · 0 production validated · ${s.anchorEligibleFamilyCount} anchor candidates.</p><p>Real top ${sec(s.realTop.score)}; null max ${sec(s.nullMax)}. ${s.separatedFamilies} retained families separated. Grid: ${esc(s.gridType)}. Near ${s.nearGridCount}; outside ${s.outsideGridCount}.</p>`;
q('#families').innerHTML=r.families.map(f=>`<article><h3>${esc(f.id)} · ${f.eventCount} canonical events (${f.eventLengthRange.join('–')} observed)</h3><p>${f.occurrenceCount} returns · prominence ${sec(f.motifProminence)} · span ${sec(f.songSpan)} · empirical max exceedance ${sec(f.empiricalSearchMaxExceedance)}</p><p>${esc(f.falseDiscoveryStatus)}. ${esc(f.approvalReason)}.</p><p class="times">Canonical relative gaps: ${f.canonicalPattern.normalizedIntervals.map(sec).join(', ')}</p><details><summary>Aligned occurrences and listening</summary>${f.occurrences.map(o=>`<p class="times"><button data-time="${o.startTime}">Listen ${sec(o.startTime)}s</button> Events ${o.eventTimes.map(sec).join(', ')}; ${esc(o.alignment)}; cost ${sec(o.alignmentCost)}; distortion ${sec(o.timingDistortion)}; acoustic ${sec(o.acousticSimilarity)}; chroma ${sec(o.chromaSimilarity)}; internal timing ${o.internallyStable?'stable':'exploratory'}.</p>`).join('')}</details></article>`).join('')||'<p>No retained families.</p>';
q('#controls').innerHTML='<h2>Fixed null distributions</h2>'+Object.entries(r.nullDistributions).map(([k,v])=>`<details><summary>${esc(k)} · ${v.length} realizations · top range ${sec(Math.min(...v.map(z=>z.score)))}–${sec(Math.max(...v.map(z=>z.score)))}</summary><p>These are surrogate controls, not listenable source occurrences; permuted descriptors do not reconstruct music.</p><table><tr><th>Seed</th><th>Top</th><th>Similarity</th><th>Returns</th><th>Pre-timing eligibility</th></tr>${v.map(z=>`<tr><td>${z.seed}</td><td>${sec(z.score)}</td><td>${sec(z.similarity)}</td><td>${z.occurrences}</td><td>${z.preTimingEligible}</td></tr>`).join('')}</table></details>`).join('');
q('#families').querySelectorAll('button').forEach(b=>b.onclick=()=>{const a=q('#audio');a.currentTime=Math.max(0,+b.dataset.time-.2);a.play().catch(()=>q('#status').textContent='Start playback with the audio control, then retry the occurrence button.');});}
q('#track').onchange=render;render();</script>'''.replace('DATA',data)
    (ROOT/'REPORT.html').write_text(html,encoding='utf-8')
if __name__=='__main__':build()
