"""Fixed result classification/reporting; does not read audio or run detection."""
import argparse,hashlib,json
from pathlib import Path
from dsp_base import canonical
ROOT=Path(__file__).resolve().parent
IDS=['alldat','cvb','laid-back','wanna-get-lit','need-a-bag']
def finalize(freeze_commit):
    records=[json.loads((ROOT/'results'/f'{id}.json').read_text(encoding='utf-8')) for id in IDS];cal=json.loads((ROOT/'CALIBRATION.json').read_text(encoding='utf-8'));freeze=json.loads((ROOT/'PREFLIGHT.json').read_text(encoding='utf-8'))
    specific=[r['summary']['separatedFamilies']>0 for r in records];timing=cal['strictGateSupported']
    classification='E' if all(specific[:2]) and not all(specific[2:]) else 'A' if all(specific) and timing else 'B' if timing else 'C' if all(specific) else 'D'
    state={'schema':'trackcade-micro-motif-v2-frozen-completed-research','sourceCommit':freeze['sourceCommit'],'microMotifV1Commit':freeze['microMotifV1Commit'],'externalFreezeCommit':freeze_commit,'preflightSha256':hashlib.sha256((ROOT/'PREFLIGHT.json').read_bytes()).hexdigest(),'configurationSha256':freeze['configSha256'],'analysisCodeSha256':freeze['codeSha256'],'classification':classification,'inputs':[r['input'] for r in records],'summary':{r['input']['id']:r['summary'] for r in records},'resultSha256':{id:hashlib.sha256((ROOT/'results'/f'{id}.json').read_bytes()).hexdigest() for id in IDS},'externalRunsPerSong':1,'postFreezeParameterChanges':0,'externalTrackSpecificHandling':False,'privateAudioCommitted':False,'productionIntegrationAuthorized':False,'providerCalls':0,'spendUSD':0,'stage1LabelsAccessed':False,'terminalHoldoutAccessed':False,'semanticV9Changed':False,'microMotifV1Changed':False,'pulseTapV23Changed':False,'pagesChanged':False,'status':'STOP; no integration or next experiment'}
    (ROOT/'RESEARCH_STATE.json').write_bytes(canonical(state))
    lines=['# Micro-Motif v2 — frozen five-song result',f'Classification **{classification}**. No integration. Provider calls 0; spend $0.',f'Source/v1 `{freeze["sourceCommit"]}`. Committed external method freeze `{freeze_commit}`.',f'Configuration SHA-256 `{freeze["configSha256"]}`. Exact code/input/result hashes: RESEARCH_STATE.json, PREFLIGHT.json and VERIFICATION.json.','', '## Independent synthetic validation', '|Condition|Matched|Missed|FP|Median ms|P90 ms|P95 ms|Max ms|Bias ms|Pass|','|---|---:|---:|---:|---:|---:|---:|---:|---:|---|']
    for name,row in cal['validation'].items():
        m=[row[k]*1000 if row[k] is not None else None for k in ['medianSeconds','p90Seconds','p95Seconds','maximumSeconds','signedBiasSeconds']]
        lines.append('|'+name+'|'+str(row['matched'])+'|'+str(row['missed'])+'|'+str(row['falsePositives'])+'|'+'|'.join('N/A' if v is None else f'{v:.3f}' for v in m)+'|'+str(row['passes'])+'|')
    lines+=['','Calibration gate supported: '+str(timing)+'. Internal stability and low matched timing errors cannot hide missed attacks or false detections. No recording has independent real onset ground truth; production-validated count is zero.','', '## Five-song generalization','|Track|Events|Internal stable|Strict|Near grid|Outside grid|Families|Real top|Null max|Separated|Anchors|','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|']
    for r in records:
        s=r['summary'];lines.append('|'+r['input']['id']+'|'+'|'.join(str(s[k]) for k in ['eventCount','internallyStableCount','calibrationSupportedStrictCount','nearGridCount','outsideGridCount','retainedFamilyCount'])+f'|{s["realTop"]["score"]:.6f}|{s["nullMax"]:.6f}|{s["separatedFamilies"]}|{s["anchorEligibleFamilyCount"]}|')
    lines+=['','Development near/outside uses the frozen analyzer beat evidence within 20ms. External counts use a **generic exploratory pulse proxy**, not known beats; actual on/off-beat truth is unavailable. Timing annotations do not affect matching. No external track used special handling.','', '## Track details and ablations']
    for r in records:
        id=r['input']['id'];s=r['summary'];lines+=['', '### '+id,f'Audio `{r["input"]["filename"]}`, duration {r["input"]["duration"]:.6f}s; input SHA-256 `{r["input"]["inputAudioSha256"]}`; decoded PCM `{r["input"]["decodedPcmSha256"]}`; mono {r["input"]["sampleRate"]}Hz.',f'Event density {s["eventDensityPerSecond"]:.3f}/s; canonical 2/3/4/5/6 distribution `{s["lengthDistribution"]}`. Total retained occurrences {s["occurrenceCount"]}; gapped {s["gappedAlignmentOccurrences"]}.', '|Family|Length range|Returns|Prominence|Span|Search-max exceedance|Reason|','|---|---|---:|---:|---:|---:|---|']
        for f in r['families'][:3]:lines.append(f'|{f["id"]}|{f["eventCount"]} canonical / {f["eventLengthRange"]}|{f["occurrenceCount"]}|{f["motifProminence"]:.6f}|{f["songSpan"]:.6f}|{f["empiricalSearchMaxExceedance"]:.5f}|{f["falseDiscoveryStatus"]}|')
        for kind,rows in r['nullDistributions'].items():
            scores=sorted(z['score'] for z in rows);lines.append(f'{kind}: 31 fixed realizations; top-score range {scores[0]:.6f}–{scores[-1]:.6f}, median {scores[15]:.6f}; searched-family count range {min(z["searchedFamilyCount"] for z in rows)}–{max(z["searchedFamilyCount"] for z in rows)}. Full distributions include similarity, occurrence count and pre-timing eligibility, in the track JSON/local report.')
        lines+=['|Representation|Real top|Null max|Separated retained|Returns|','|---|---:|---:|---:|---:|']
        for name,a in r['ablations'].items():lines.append(f'|{name}|{a["realTop"]["score"]:.6f}|{a["nullMax"]:.6f}|{a["separatedFamilies"]}|{a["occurrences"]}|')
        lines.append('Chroma and HP are supported only to the extent of this measured ablation separation; neither validates note pitch or foreground/source identity. Source UNKNOWN.')
    lines+=['','## v1 comparison and ALLDAT three-event question']
    repo=ROOT.parents[1]
    for r in records[:2]:
        id=r['input']['id'];old=json.loads((repo/f'research/micro-motif-v1/results/{id}-summary.json').read_text(encoding='utf-8'));s=r['summary'];lines.append(f'{id}: v1 {old["eventCount"]} events, {old["provisionalTimingGateCount"]} provisional gates, {old["familyCount"]} display-capped families. v2 {s["eventCount"]} events, {s["internallyStableCount"]} internal gates, {s["retainedFamilyCount"]} retained families, {s["separatedFamilies"]} null-separated. Candidate count reduction alone is not proven false-family reduction: v2 search sampling/alignment/representation differ. Same-search ablations are the more controlled feature comparison.')
    lines+=['ALLDAT three-event candidates are reported only as blind numerical recurrence. If present, gapped matching improves tolerance; no source/perceptual correspondence or validated improvement is claimed without null separation. No subjective timestamps were used.','', '## Multiplicity, eligibility and coverage','The per-track plus-one maximum-surrogate screen covers all searched candidate families before display suppression, across three controls and 31 seeds. <=.05 is required. It is not a proven statistical FDR or calibrated probability. Search caps and surrogate exchangeability are evidence limitations. Exact rates, maxima and reasons are in each family JSON.','No live gameplay selection was generated. Coverage lists are empty if no research anchor family passes; that means no newly validated motif coverage claim is available, not that existing gameplay has zero coverage. External live baseline is N/A.','', '## Remaining gaps / integrity','Independent real onset truth/stems are absent. Synthetic failures, mixture/source ambiguity, weak null separation, finite surrogate resolution, sampled motif search, one-interior-gap limits and lack of human blind motif ground truth remain. Titles/lyrics/genre/artwork never guide computation. No compiler or Analyzer was invoked. v1, V9, Pulse Tap v2.3 and Pages remain unchanged; Stage1 labels and terminal holdout untouched. Private MP3s/PCM were neither copied into nor tracked by the repository.','Local five-song inspection: use README instructions and the explicit scratch input map with review-server.cjs; open http://127.0.0.1:8767/. REPORT.html embeds only derived numerical results. Audio routes bind loopback and read originals from explicit paths.','**STOP.** No integration, visuals, publishing private audio or next experiment.']
    (ROOT/'RESULTS.md').write_text('\n'.join(lines)+'\n',encoding='utf-8');print(classification)
if __name__=='__main__':
    ap=argparse.ArgumentParser();ap.add_argument('--freeze-commit',required=True);a=ap.parse_args();finalize(a.freeze_commit)
